// Copyright (c) 2020-present, author: Zhengyang Liu (liuz@cs.utah.edu).
// Distributed under the MIT license that can be found in the LICENSE file.

TOKEN(END)
TOKEN(COMMA)
TOKEN(LPAREN)
TOKEN(RPAREN)
TOKEN(LCURLY)
TOKEN(RCURLY)

TOKEN(BAND)
TOKEN(BOR)
TOKEN(BXOR)
TOKEN(ADD)
TOKEN(SUB)
TOKEN(MUL)
TOKEN(SDIV)
TOKEN(UDIV)
TOKEN(LSHR)
TOKEN(ASHR)
TOKEN(SHL)

TOKEN(VAR)
TOKEN(CONST)

TOKEN(NUM_STR)
TOKEN(BITS)

TOKEN(REGISTER)
TOKEN(INT_TYPE)
TOKEN(VECTOR_TYPE_PREFIX)
TOKEN(CSGT)